# Generated by Django 5.2 on 2025-05-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_created_at_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, '最優先'), (2, '重要'), (3, '普通'), (4, '低')], default=3),
        ),
    ]
